# Generated by Django 4.0.1 on 2022-02-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_created_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
